### ISSUE TITLE
Getting Error while deploy the Explorer on network

### ISSUE THREAD

**Issue by abhisamant7** [feitnomore/hyperledger-fabric-kubernetes#11]
I am getting error while deploy hyperledger explorer on cluster as deployment 
```

false 'ssl-certs' '/opt/explorer/ssl-certs'
postgres://hppoc:password@blockchain-explorer-db:5432/fabricexplorer
error when connecting to db: { Error: connect ECONNREFUSED 100.68.123.247:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '100.68.123.247',
  port: 5432 }
******* Initialization started for hyperledger fabric platform ******, undefined
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
TypeError: Cannot read property 'size' of undefined
    at Platform.initialize (/opt/explorer/app/platform/fabric/Platform.js:75:42)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error when connecting to db: TypeError: Cannot read property 'on' of undefined
    at Timeout.handleDisconnect [as _onTimeout] (/opt/explorer/app/persistence/postgreSQL/PgService.js:68:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
TypeError: "callback" argument must be a function
    at setTimeout (timers.js:450:11)
    at Timeout.handleDisconnect [as _onTimeout] (/opt/explorer/app/persistence/postgreSQL/PgService.js:85:5)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Received kill signal, shutting down gracefully
Closed out connections

```

**Comment by feitnomore** [comment]
I'm not really able to support hyperledger-explorer issues. First you should check if you database, postgresql is really running on 100.68.123.247. This doesn't seem accurate, might be a networking problem/dns. Seems like your explorer is not able to reach the database.
Thanks
